<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap Site</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
        integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
        integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
        crossorigin="anonymous"></script>
</head>
<body class="container">
    <secttion class="row mt-5">
        <div class="text-center p-4 col-md-4 offset-md-4 mt-5 mb-4 text-white rounded bg-dark">
            <h1>Login</h1>
            <form method="POST">
                <div class='mb-3 text-light'>
                    <label for='email' class='form-label'>Email</label>
                    <input type='email' name="email" class='form-control' id='email' aria-describedby='emailHelp'>
                    <div id='emailHelp' class='form-text'>Nós nunca compartilhamos suas informações.</div>
                </div>
                <?php App\Notification\WebNotification::show();?>
                <div class='mb-3 text-light'>
                    <label for='password' class='form-label'>Password</label>
                    <input type='password' name="password" class='form-control' id='password'>
                </div>
                <button type='submit' class='btn btn-primary d-grid'>Log in</button>
            </form>
        </div>
    </secttion>
</body>

</html>