<?php 
    $usuario = $dados[0];
?>
<section class="mt-3 card card-body">
    <h1>Editar Usuario</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $usuario->nome; ?>">

                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3" value="<?php echo $usuario->email; ?>">

                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>