<?php 
    $aluno = $dados[0];
?>
<section class="mt-3 card card-body">
    <h1>Editar Professor</h1>
    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $aluno->nome; ?>">

                <label for="endereco">Endereço</label>
                <input name="endereco" type="text" id="endereco" class="form-control mb-3" value="<?php echo $aluno->endereco; ?>">

                <label for="cpf">CPF</label>
                <input name="cpf" type="text" id="cpf" class="form-control mb-3" value="<?php echo $aluno->cpf; ?>">

                <label for="formacao">Formação</label>
                <input name="formacao" type="text" id="formacao" class="form-control mb-3" value="<?php echo $aluno->formacao; ?>">


                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>