<section class="mt-3 card card-body">
    <h1>Gerenciar Professor</h1>

    <div class="mt-2">
        <a href="/professores/novo" class="btn btn-outline-dark btn-sm">Novo Professor</a>

        <a href="/professores/relatorio" target="_blank" class="btn btn-outline-dark btn-sm">Gerar Relatorio de Professores em PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Endereço</th>
                <th>Formação</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                // if(isset($professores) && sizeOf($professores) > 0){
                    foreach ($professores ?? [] as $professor) {
                        echo "
                            <tr>
                                <td>{$professor->id}</td>
                                <td>{$professor->nome}</td>
                                <td>{$professor->endereco}</td>
                                <td>{$professor->formacao}</td>
                                <td>
                                    <a href='/professores/editar?id={$professor->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                                    <a href='/professores/excluir?id={$professor->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                                </td>
                            </tr>
                        ";
                    }
                // }
            ?>
        </tbody>
    </table>
</section>