<nav class="mt-3 d-flex justify-content-between">
    <div class="text-start">
        <a href="/" class="btn btn-outline-dark">Inicio</a>

        
        <a href="/alunos/listar" class="btn btn-outline-dark">Alunos</a>
        
        <a href="/professores/listar" class="btn btn-outline-dark">Professor</a>
        
        <a href="/cursos/listar" class="btn btn-outline-dark">Cursos</a> 
        
        <a href="/categorias/listar" class="btn btn-outline-dark">Categorias</a>
        
        <a href="/usuarios/listar" class="btn btn-outline-dark">Usuarios</a> 
    </div>
    <div class="d-flex">
        <p class=" me-2 pt-2">Bem Vindo(a) <?php echo App\Security\UserSecurity::getUser()->name ?></p>
        <div class="  ms-2 pt-1 text-end">
            <a href="/desconectar" class="btn btn-outline-danger">Desconectar</a>
        </div>
    </div>
</nav>

<hr>