<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">

                <label for="descricao">Descrição</label>
                <input name="descricao" type="text" id="email" class="form-control mb-3">

                <label for="cargaHoraria">Carga Horária</label>
                <input name="cargaHoraria" type="text" id="cpf" class="form-control mb-3">

                <label for="categoria">Categoria</label>
                <select name="categoria" class="form-control mb-3">
                    <?php
                        foreach($categorias as $categoria){
                            echo "
                                <option value='{$categoria->id}'>{$categoria->nome}</option>
                            ";
                        }
                    ?>
                </select>
                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>