<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>

    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark">Novo Curso</a>
        <a href="/cursos/relatorio" target="_blank" class="btn btn-outline-dark btn">Gerar Relatorio de cursos em PDF</a>

    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                if(isset($cursos) && sizeOf($cursos) > 0){
                    foreach ($cursos as $curso) {
                        echo "
                            <tr>
                                <td>{$curso['curso_id']}</td>
                                <td>{$curso['curso_nome']}</td>
                                <td>{$curso['categoria_nome']}</td>
                                <td>{$curso['curso_descricao']}</td>
                                <td>
                                    <a href='/cursos/editar?id={$curso['curso_id']}' class='btn btn-warning'>Editar</a>
                                    <a href='/cursos/excluir?id={$curso['curso_id']}' class='btn btn-danger'>Deletar</a>
                                </td>
                            </tr>
                        ";
                    }
                }
            ?>
        </tbody>
    </table>
</section>